perl -p -i -e "s/GsParameter.get('CALLFORWARD_DESTINATION_DEFAULT')/GsParameter.get('GsParameter.get('CALLFORWARD_DESTINATION_DEFAULT')')/g" `grep -ril GsParameter.get('CALLFORWARD_DESTINATION_DEFAULT') *`
perl -p -i -e "s/GsParameter.get('CALLFORWARD_RULES_ACT_PER_SIP_ACCOUNT_DEFAULT')/GsParameter.get('GsParameter.get('CALLFORWARD_RULES_ACT_PER_SIP_ACCOUNT_DEFAULT')')/g" `grep -ril GsParameter.get('CALLFORWARD_RULES_ACT_PER_SIP_ACCOUNT_DEFAULT') *`
perl -p -i -e "s/GsParameter.get('CALLTHROUGH_HAS_WHITELISTS')/GsParameter.get('GsParameter.get('CALLTHROUGH_HAS_WHITELISTS')')/g" `grep -ril GsParameter.get('CALLTHROUGH_HAS_WHITELISTS') *`
perl -p -i -e "s/GsParameter.get('CALLTHROUGH_NAME_TO_BE_USED_FOR_DEFAULT_ACTIVATION')/GsParameter.get('GsParameter.get('CALLTHROUGH_NAME_TO_BE_USED_FOR_DEFAULT_ACTIVATION')')/g" `grep -ril GsParameter.get('CALLTHROUGH_NAME_TO_BE_USED_FOR_DEFAULT_ACTIVATION') *`
perl -p -i -e "s/GsParameter.get('CALL_WAITING')/GsParameter.get('GsParameter.get('CALL_WAITING')')/g" `grep -ril GsParameter.get('CALL_WAITING') *`
perl -p -i -e "s/GsParameter.get('DAYS_TILL_AUTO_DELETE')/GsParameter.get('GsParameter.get('DAYS_TILL_AUTO_DELETE')')/g" `grep -ril GsParameter.get('DAYS_TILL_AUTO_DELETE') *`
perl -p -i -e "s/GsParameter.get('DEFAULT_API_TENANT_ID')/GsParameter.get('GsParameter.get('DEFAULT_API_TENANT_ID')')/g" `grep -ril GsParameter.get('DEFAULT_API_TENANT_ID') *`
perl -p -i -e "s/GsParameter.get('DEFAULT_CALL_FORWARD_DEPTH')/GsParameter.get('GsParameter.get('DEFAULT_CALL_FORWARD_DEPTH')')/g" `grep -ril GsParameter.get('DEFAULT_CALL_FORWARD_DEPTH') *`
perl -p -i -e "s/GsParameter.get('DEFAULT_CLIP_SETTING')/GsParameter.get('GsParameter.get('DEFAULT_CLIP_SETTING')')/g" `grep -ril GsParameter.get('DEFAULT_CLIP_SETTING') *`
perl -p -i -e "s/GsParameter.get('DEFAULT_CLIR_SETTING')/GsParameter.get('GsParameter.get('DEFAULT_CLIR_SETTING')')/g" `grep -ril GsParameter.get('DEFAULT_CLIR_SETTING') *`
perl -p -i -e "s/GsParameter.get('DEFAULT_LENGTH_SIP_AUTH_NAME')/GsParameter.get('GsParameter.get('DEFAULT_LENGTH_SIP_AUTH_NAME')')/g" `grep -ril GsParameter.get('DEFAULT_LENGTH_SIP_AUTH_NAME') *`
perl -p -i -e "s/GsParameter.get('DEFAULT_LENGTH_SIP_PASSWORD')/GsParameter.get('GsParameter.get('DEFAULT_LENGTH_SIP_PASSWORD')')/g" `grep -ril GsParameter.get('DEFAULT_LENGTH_SIP_PASSWORD') *`
perl -p -i -e "s/GsParameter.get('DEFAULT_MAX_CONFERENCE_MEMBERS')/GsParameter.get('GsParameter.get('DEFAULT_MAX_CONFERENCE_MEMBERS')')/g" `grep -ril GsParameter.get('DEFAULT_MAX_CONFERENCE_MEMBERS') *`
perl -p -i -e "s/GsParameter.get('DEFAULT_NUMBER_OF_RETRIES')/GsParameter.get('GsParameter.get('DEFAULT_NUMBER_OF_RETRIES')')/g" `grep -ril GsParameter.get('DEFAULT_NUMBER_OF_RETRIES') *`
perl -p -i -e "s/GsParameter.get('DEFAULT_PAGINATION_ENTRIES_PER_PAGE')/GsParameter.get('GsParameter.get('DEFAULT_PAGINATION_ENTRIES_PER_PAGE')')/g" `grep -ril GsParameter.get('DEFAULT_PAGINATION_ENTRIES_PER_PAGE') *`
perl -p -i -e "s/GsParameter.get('DIRECT_INWARD_DIALING_NUMBERS')/GsParameter.get('GsParameter.get('DIRECT_INWARD_DIALING_NUMBERS')')/g" `grep -ril GsParameter.get('DIRECT_INWARD_DIALING_NUMBERS') *`
perl -p -i -e "s/GsParameter.get('DOUBLE_CHECK_POSITIVE_USERS_CSV')/GsParameter.get('GsParameter.get('DOUBLE_CHECK_POSITIVE_USERS_CSV')')/g" `grep -ril GsParameter.get('DOUBLE_CHECK_POSITIVE_USERS_CSV') *`
perl -p -i -e "s/GsParameter.get('GEMEINSCHAFT_VERSION')/GsParameter.get('GsParameter.get('GEMEINSCHAFT_VERSION')')/g" `grep -ril GsParameter.get('GEMEINSCHAFT_VERSION') *`
perl -p -i -e "s/GsParameter.get('GUI_REDIRECT_HTTPS')/GsParameter.get('GsParameter.get('GUI_REDIRECT_HTTPS')')/g" `grep -ril GsParameter.get('GUI_REDIRECT_HTTPS') *`
perl -p -i -e "s/GsParameter.get('HOMEBASE_IP_ADDRESS')/GsParameter.get('GsParameter.get('HOMEBASE_IP_ADDRESS')')/g" `grep -ril GsParameter.get('HOMEBASE_IP_ADDRESS') *`
perl -p -i -e "s/GsParameter.get('HUNT_GROUP_STRATEGIES')/GsParameter.get('GsParameter.get('HUNT_GROUP_STRATEGIES')')/g" `grep -ril GsParameter.get('HUNT_GROUP_STRATEGIES') *`
perl -p -i -e "s/GsParameter.get('IMPORT_CSV_ENCODING')/GsParameter.get('GsParameter.get('IMPORT_CSV_ENCODING')')/g" `grep -ril GsParameter.get('IMPORT_CSV_ENCODING') *`
perl -p -i -e "s/GsParameter.get('IMPORT_CSV_FILE')/GsParameter.get('GsParameter.get('IMPORT_CSV_FILE')')/g" `grep -ril GsParameter.get('IMPORT_CSV_FILE') *`
perl -p -i -e "s/GsParameter.get('INTERNAL_EXTENSIONS')/GsParameter.get('GsParameter.get('INTERNAL_EXTENSIONS')')/g" `grep -ril GsParameter.get('INTERNAL_EXTENSIONS') *`
perl -p -i -e "s/GsParameter.get('MAXIMUM_NUMBER_OF_PEOPLE_IN_A_CONFERENCE')/GsParameter.get('GsParameter.get('MAXIMUM_NUMBER_OF_PEOPLE_IN_A_CONFERENCE')')/g" `grep -ril GsParameter.get('MAXIMUM_NUMBER_OF_PEOPLE_IN_A_CONFERENCE') *`
perl -p -i -e "s/GsParameter.get('MAXIMUM_PIN_LENGTH')/GsParameter.get('GsParameter.get('MAXIMUM_PIN_LENGTH')')/g" `grep -ril GsParameter.get('MAXIMUM_PIN_LENGTH') *`
perl -p -i -e "s/GsParameter.get('MAX_CALL_FORWARD_DEPTH')/GsParameter.get('GsParameter.get('MAX_CALL_FORWARD_DEPTH')')/g" `grep -ril GsParameter.get('MAX_CALL_FORWARD_DEPTH') *`
perl -p -i -e "s/GsParameter.get('MAX_EXTENSION_LENGTH')/GsParameter.get('GsParameter.get('MAX_EXTENSION_LENGTH')')/g" `grep -ril GsParameter.get('MAX_EXTENSION_LENGTH') *`
perl -p -i -e "s/GsParameter.get('MINIMUM_PIN_LENGTH')/GsParameter.get('GsParameter.get('MINIMUM_PIN_LENGTH')')/g" `grep -ril GsParameter.get('MINIMUM_PIN_LENGTH') *`
perl -p -i -e "s/GsParameter.get('NIGHTLY_REBOOT_OF_PHONES')/GsParameter.get('GsParameter.get('NIGHTLY_REBOOT_OF_PHONES')')/g" `grep -ril GsParameter.get('NIGHTLY_REBOOT_OF_PHONES') *`
perl -p -i -e "s/GsParameter.get('PROVISIONING_AUTO_ADD_PHONE')/GsParameter.get('GsParameter.get('PROVISIONING_AUTO_ADD_PHONE')')/g" `grep -ril GsParameter.get('PROVISIONING_AUTO_ADD_PHONE') *`
perl -p -i -e "s/GsParameter.get('PROVISIONING_AUTO_ADD_SIP_ACCOUNT')/GsParameter.get('GsParameter.get('PROVISIONING_AUTO_ADD_SIP_ACCOUNT')')/g" `grep -ril GsParameter.get('PROVISIONING_AUTO_ADD_SIP_ACCOUNT') *`
perl -p -i -e "s/GsParameter.get('PROVISIONING_AUTO_SIP_ACCOUNT_CALLER_PREFIX')/GsParameter.get('GsParameter.get('PROVISIONING_AUTO_SIP_ACCOUNT_CALLER_PREFIX')')/g" `grep -ril GsParameter.get('PROVISIONING_AUTO_SIP_ACCOUNT_CALLER_PREFIX') *`
perl -p -i -e "s/GsParameter.get('PROVISIONING_AUTO_TENANT_ID')/GsParameter.get('GsParameter.get('PROVISIONING_AUTO_TENANT_ID')')/g" `grep -ril GsParameter.get('PROVISIONING_AUTO_TENANT_ID') *`
perl -p -i -e "s/GsParameter.get('PROVISIONING_IEEE8021X_EAP_PASSWORD')/GsParameter.get('GsParameter.get('PROVISIONING_IEEE8021X_EAP_PASSWORD')')/g" `grep -ril GsParameter.get('PROVISIONING_IEEE8021X_EAP_PASSWORD') *`
perl -p -i -e "s/GsParameter.get('PROVISIONING_IEEE8021X_EAP_USERNAME')/GsParameter.get('GsParameter.get('PROVISIONING_IEEE8021X_EAP_USERNAME')')/g" `grep -ril GsParameter.get('PROVISIONING_IEEE8021X_EAP_USERNAME') *`
perl -p -i -e "s/GsParameter.get('REMOTE_IP_ADDRESS_WHITELIST')/GsParameter.get('GsParameter.get('REMOTE_IP_ADDRESS_WHITELIST')')/g" `grep -ril GsParameter.get('REMOTE_IP_ADDRESS_WHITELIST') *`
perl -p -i -e "s/GsParameter.get('SERVICE_NUMBERS')/GsParameter.get('GsParameter.get('SERVICE_NUMBERS')')/g" `grep -ril GsParameter.get('SERVICE_NUMBERS') *`
perl -p -i -e "s/GsParameter.get('SIEMENS_HISTORY_RELOAD_TIMES')/GsParameter.get('GsParameter.get('SIEMENS_HISTORY_RELOAD_TIMES')')/g" `grep -ril GsParameter.get('SIEMENS_HISTORY_RELOAD_TIMES') *`
perl -p -i -e "s/GsParameter.get('STRICT_DID_HANDLING')/GsParameter.get('GsParameter.get('STRICT_DID_HANDLING')')/g" `grep -ril GsParameter.get('STRICT_DID_HANDLING') *`
perl -p -i -e "s/GsParameter.get('STRICT_INTERNAL_EXTENSION_HANDLING')/GsParameter.get('GsParameter.get('STRICT_INTERNAL_EXTENSION_HANDLING')')/g" `grep -ril GsParameter.get('STRICT_INTERNAL_EXTENSION_HANDLING') *`
perl -p -i -e "s/GsParameter.get('SUPER_TENANT_NAME')/GsParameter.get('GsParameter.get('SUPER_TENANT_NAME')')/g" `grep -ril GsParameter.get('SUPER_TENANT_NAME') *`
perl -p -i -e "s/GsParameter.get('TO_S_MAX_CALLER_NAME_LENGTH')/GsParameter.get('GsParameter.get('TO_S_MAX_CALLER_NAME_LENGTH')')/g" `grep -ril GsParameter.get('TO_S_MAX_CALLER_NAME_LENGTH') *`
perl -p -i -e "s/GsParameter.get('TO_S_MAX_LENGTH_OF_AUTH_NAME')/GsParameter.get('GsParameter.get('TO_S_MAX_LENGTH_OF_AUTH_NAME')')/g" `grep -ril GsParameter.get('TO_S_MAX_LENGTH_OF_AUTH_NAME') *`
perl -p -i -e "s/GsParameter.get('USER_NAME_PREFIX')/GsParameter.get('GsParameter.get('USER_NAME_PREFIX')')/g" `grep -ril GsParameter.get('USER_NAME_PREFIX') *`
perl -p -i -e "s/GsParameter.get('VALID_SECONDS_BETWEEN_JUMPS_VALUES')/GsParameter.get('GsParameter.get('VALID_SECONDS_BETWEEN_JUMPS_VALUES')')/g" `grep -ril GsParameter.get('VALID_SECONDS_BETWEEN_JUMPS_VALUES') *`
perl -p -i -e "s/GsParameter.get('WRITE_GS_CLUSTER_SYNC_LOG')/GsParameter.get('GsParameter.get('WRITE_GS_CLUSTER_SYNC_LOG')')/g" `grep -ril GsParameter.get('WRITE_GS_CLUSTER_SYNC_LOG') *`
