development:
  server: "http://192.168.9.106/faye"
  secret_token: "GajvacjefEchIOmtErigWadJuommemexNenvacneerjinanyorryedvegEphtub5"
test:
  server: "http://192.168.9.106/faye"
  secret_token: "GajvacjefEchIOmtErigWadJuommemexNenvacneerjinanyorryedvegEphtub5"
production:
  server: "http://192.168.9.106/faye"
  secret_token: "GajvacjefEchIOmtErigWadJuommemexNenvacneerjinanyorryedvegEphtub5"
  signature_expiration: 3600 # one hour
