# ruby encoding: utf-8

class CountryDefaults < ActiveRecord::Migration
  def up
    ################################################################
    # Countries
    ################################################################

    ActiveRecord::Base.transaction do
      Country.create(:name => "American Samoa", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Anguilla", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Antigua and Barbuda", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Bahamas", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Barbados", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Bermuda", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "British Virgin Islands", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Canada", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Cayman Islands", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Dominica", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Dominican Republic", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Grenada", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Guam", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Jamaica", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Montserrat", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Northern Mariana Islands", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Puerto Rico", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Saint Kitts and Nevis", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Saint Lucia", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Saint Vincent and the Grenadines", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Trinidad and Tobago", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Turks and Caicos Islands", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "United States of America", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "United States Virgin Islands", :country_code => "1",  :international_call_prefix => "011", :trunk_prefix => "1" )
      Country.create(:name => "Egypt", :country_code => "20",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Morocco", :country_code => "212",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Algeria", :country_code => "213",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Tunisia", :country_code => "216",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Libya", :country_code => "218",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Gambia", :country_code => "220",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Senegal", :country_code => "221",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Mauritania", :country_code => "222",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Mali", :country_code => "223",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Guinea", :country_code => "224",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Côte d'Ivoire", :country_code => "225",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Burkina Faso", :country_code => "226",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Niger", :country_code => "227",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Togolese Republic", :country_code => "228",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Benin", :country_code => "229",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Mauritius", :country_code => "230",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Liberia", :country_code => "231",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Sierra Leone", :country_code => "232",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Ghana", :country_code => "233",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Nigeria", :country_code => "234",  :international_call_prefix => "009", :trunk_prefix => "" )
      Country.create(:name => "Chad", :country_code => "235",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Central African Republic", :country_code => "236",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Cameroon", :country_code => "237",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Cape Verde", :country_code => "238",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Sao Tome and Principe", :country_code => "239",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Equatorial Guinea", :country_code => "240",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Gabonese Republic", :country_code => "241",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Congo", :country_code => "242",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Democratic Republic of the Congo", :country_code => "243",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Angola", :country_code => "244",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Guinea-Bissau", :country_code => "245",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Diego Garcia", :country_code => "246",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Ascension", :country_code => "247",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Seychelles", :country_code => "248",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Sudan", :country_code => "249",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Rwanda", :country_code => "250",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Ethiopia", :country_code => "251",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Somali Democratic Republic", :country_code => "252",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Djibouti", :country_code => "253",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Kenya", :country_code => "254",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Tanzania", :country_code => "255",  :international_call_prefix => "000", :trunk_prefix => "" )
      Country.create(:name => "Uganda", :country_code => "256",  :international_call_prefix => "000", :trunk_prefix => "" )
      Country.create(:name => "Burundi", :country_code => "257",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Mozambique", :country_code => "258",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Zambia", :country_code => "260",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Madagascar", :country_code => "261",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Reunion", :country_code => "262",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Zimbabwe", :country_code => "263",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Namibia", :country_code => "264",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Malawi", :country_code => "265",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Lesotho", :country_code => "266",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Botswana", :country_code => "267",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Swaziland", :country_code => "268",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Comoros", :country_code => "269",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Mayotte", :country_code => "269",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "South Africa", :country_code => "27",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Saint Helena", :country_code => "290",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Eritrea", :country_code => "291",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Aruba", :country_code => "297",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Faroe Islands", :country_code => "298",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Greenland", :country_code => "299",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Greece", :country_code => "30",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Netherlands", :country_code => "31",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Belgium", :country_code => "32",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "France", :country_code => "33",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Spain", :country_code => "34",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Gibraltar", :country_code => "350",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Portugal", :country_code => "351",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Luxembourg", :country_code => "352",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Ireland", :country_code => "353",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Iceland", :country_code => "354",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Albania", :country_code => "355",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Malta", :country_code => "356",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Cyprus", :country_code => "357",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Finland", :country_code => "358",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Bulgaria", :country_code => "359",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Hungary", :country_code => "36",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Lithuania", :country_code => "370",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Latvia", :country_code => "371",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Estonia", :country_code => "372",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Moldova", :country_code => "373",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Armenia", :country_code => "374",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Belarus", :country_code => "375",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Andorra", :country_code => "376",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Monaco", :country_code => "377",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "San Marino", :country_code => "378",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Vatican City State", :country_code => "379",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Ukraine", :country_code => "380",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Serbia and Montenegro", :country_code => "381",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Croatia", :country_code => "385",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Slovenia", :country_code => "386",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Bosnia and Herzegovina", :country_code => "387",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Group of countries, shared code", :country_code => "388",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "The Former Yugoslav Republic of Macedonia", :country_code => "389",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Italy", :country_code => "39",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Vatican City State", :country_code => "39",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Romania", :country_code => "40",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Switzerland", :country_code => "41",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Czech Republic", :country_code => "420",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Slovak Republic", :country_code => "421",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Liechtenstein", :country_code => "423",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Austria", :country_code => "43",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "United Kingdom of Great Britain and Northern Ireland", :country_code => "44",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Denmark", :country_code => "45",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Sweden", :country_code => "46",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Norway", :country_code => "47",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Poland", :country_code => "48",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Germany", :country_code => "49",  :international_call_prefix => "00", :trunk_prefix => "0" )
      Country.create(:name => "Falkland Islands", :country_code => "500",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Belize", :country_code => "501",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Guatemala", :country_code => "502",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "El Salvador", :country_code => "503",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Honduras", :country_code => "504",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Nicaragua", :country_code => "505",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Costa Rica", :country_code => "506",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Panama", :country_code => "507",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Saint Pierre and Miquelon", :country_code => "508",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Haiti", :country_code => "509",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Peru", :country_code => "51",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Mexico", :country_code => "52",  :international_call_prefix => "00", :trunk_prefix => "01" )
      Country.create(:name => "Cuba", :country_code => "53",  :international_call_prefix => "119", :trunk_prefix => "" )
      Country.create(:name => "Argentine Republic", :country_code => "54",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Brazil", :country_code => "55",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Chile", :country_code => "56",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Colombia", :country_code => "57",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Venezuela", :country_code => "58",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Guadeloupe", :country_code => "590",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Bolivia", :country_code => "591",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Guyana", :country_code => "592",  :international_call_prefix => "001", :trunk_prefix => "" )
      Country.create(:name => "Ecuador", :country_code => "593",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "French Guiana", :country_code => "594",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Paraguay", :country_code => "595",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Martinique", :country_code => "596",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Suriname", :country_code => "597",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Uruguay", :country_code => "598",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Netherlands Antilles", :country_code => "599",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Malaysia", :country_code => "60",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Australia", :country_code => "61",  :international_call_prefix => "0011", :trunk_prefix => "" )
      Country.create(:name => "Indonesia", :country_code => "62",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Philippines", :country_code => "63",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "New Zealand", :country_code => "64",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Singapore", :country_code => "65",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Thailand", :country_code => "66",  :international_call_prefix => "001", :trunk_prefix => "" )
      Country.create(:name => "Democratic Republic of Timor-Leste", :country_code => "670",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Australian External Territories", :country_code => "672",  :international_call_prefix => "0011", :trunk_prefix => "" )
      Country.create(:name => "Brunei Darussalam", :country_code => "673",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Nauru", :country_code => "674",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Papua New Guinea", :country_code => "675",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Tonga", :country_code => "676",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Solomon Islands", :country_code => "677",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Vanuatu", :country_code => "678",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Fiji", :country_code => "679",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Palau", :country_code => "680",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Wallis and Futuna", :country_code => "681",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Cook Islands", :country_code => "682",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Niue", :country_code => "683",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Samoa", :country_code => "685",  :international_call_prefix => "0", :trunk_prefix => "" )
      Country.create(:name => "Kiribati", :country_code => "686",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "New Caledonia", :country_code => "687",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Tuvalu", :country_code => "688",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "French Polynesia", :country_code => "689",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Tokelau", :country_code => "690",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Micronesia", :country_code => "691",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Marshall Islands", :country_code => "692",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Kazakhstan", :country_code => "7",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Russian Federation", :country_code => "7",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "International Freephone Service", :country_code => "800",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "International Shared Cost Service", :country_code => "808",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Japan", :country_code => "81",  :international_call_prefix => "010", :trunk_prefix => "" )
      Country.create(:name => "Korea", :country_code => "82",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Viet Nam", :country_code => "84",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Democratic People's Republic of Korea", :country_code => "850",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Hong Kong, China", :country_code => "852",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Macao, China", :country_code => "853",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Cambodia", :country_code => "855",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Lao People's Democratic Republic", :country_code => "856",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "China", :country_code => "86",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Inmarsat SNAC", :country_code => "870",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Inmarsat (871)", :country_code => "871",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Inmarsat (872)", :country_code => "872",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Inmarsat (873)", :country_code => "873",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Inmarsat (874)", :country_code => "874",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Universal Personal Telecommunication Service", :country_code => "878",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Bangladesh", :country_code => "880",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Turkey", :country_code => "90",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "India", :country_code => "91",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Pakistan", :country_code => "92",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Afghanistan", :country_code => "93",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Sri Lanka", :country_code => "94",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Myanmar", :country_code => "95",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Maldives", :country_code => "960",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Lebanon", :country_code => "961",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Jordan", :country_code => "962",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Syrian Arab Republic", :country_code => "963",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Iraq", :country_code => "964",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Kuwait", :country_code => "965",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Saudi Arabia", :country_code => "966",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Yemen", :country_code => "967",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Oman", :country_code => "968",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "United Arab Emirates", :country_code => "971",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Israel", :country_code => "972",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Bahrain", :country_code => "973",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Qatar", :country_code => "974",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Bhutan", :country_code => "975",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Mongolia", :country_code => "976",  :international_call_prefix => "001", :trunk_prefix => "" )
      Country.create(:name => "Nepal", :country_code => "977",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "International Premium Rate Service", :country_code => "979",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Iran", :country_code => "98",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Tajikistan", :country_code => "992",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Turkmenistan", :country_code => "993",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Azerbaijani Republic", :country_code => "994",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Georgia", :country_code => "995",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Kyrgyz Republic", :country_code => "996",  :international_call_prefix => "00", :trunk_prefix => "" )
      Country.create(:name => "Uzbekistan", :country_code => "998",  :international_call_prefix => "00", :trunk_prefix => "" )
    end
  end

  def down
    Country.destroy_all
  end
end
